/* Shared app-page behaviour: the latest-version download button and the
   release notes table.

   Each app page may ship a releases.js data file next to it that sets
   window.APP_RELEASES. For apps built here, that file is regenerated by the
   app's CI on every release, so the page never needs editing when a version
   ships. It is a script rather than fetched JSON so the page also works when
   opened straight from disk. Apps with no releases yet simply omit the file and
   get the "coming soon" empty state. */
(function () {
  "use strict";

  var PAGE_SIZE = 10;
  var RELEASES_URL = "https://github.com/CaiqueCosta/cpop-studio/releases";

  var tableBody = document.querySelector("[data-releases-body]");
  var pager = document.querySelector("[data-releases-pager]");
  var pagerStatus = document.querySelector("[data-releases-status]");
  var prevButton = document.querySelector("[data-releases-prev]");
  var nextButton = document.querySelector("[data-releases-next]");
  var downloadButton = document.querySelector("[data-latest-download]");
  var summaryLine = document.querySelector("[data-latest-summary]");

  var releases = [];
  var page = 0;

  function escapeHtml(value) {
    return String(value == null ? "" : value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }

  function formatDate(value) {
    if (!value) return "Unknown date";
    var date = new Date(value);
    if (isNaN(date.getTime())) return value;
    return new Intl.DateTimeFormat("en", {
      month: "short",
      day: "numeric",
      year: "numeric"
    }).format(date);
  }

  function versionLabel(release) {
    return release.version ? "v" + release.version : release.name || "Untitled release";
  }

  // Everything is escaped before any markup is added, so release bodies coming
  // from GitHub can never inject HTML.
  function inline(text) {
    return escapeHtml(text).replace(/`([^`]+)`/g, "<code>$1</code>");
  }

  // Release bodies usually open with a title heading ("# Bittersweet 0.1.1")
  // that the version column already says — drop it so the cell starts with the
  // actual change. Any heading ending in this release's version counts.
  function stripTitleHeading(markdown, release) {
    var lines = String(markdown || "").split(/\r?\n/);
    while (lines.length && !lines[0].trim()) lines.shift();

    var heading = (lines[0] || "").trim().match(/^#{1,3}\s+(.+)$/);
    var version = String(release.version || "").trim();
    if (heading && version) {
      var text = heading[1].trim();
      if (text === version || text.slice(-version.length - 1) === " " + version ||
          text.slice(-version.length - 2) === " v" + version) {
        lines.shift();
      }
    }

    return lines.join("\n");
  }

  function platformLabel(release) {
    return release.platform || release.minimumMacOS || "";
  }

  function markdownToHtml(markdown) {
    var lines = String(markdown || "").split(/\r?\n/);
    var html = "";
    var inList = false;

    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();

      if (!line) {
        if (inList) {
          html += "</ul>";
          inList = false;
        }
        continue;
      }

      if (line.indexOf("- ") === 0 || line.indexOf("* ") === 0) {
        if (!inList) {
          html += "<ul>";
          inList = true;
        }
        html += "<li>" + inline(line.slice(2)) + "</li>";
        continue;
      }

      if (inList) {
        html += "</ul>";
        inList = false;
      }

      var heading = line.match(/^#{1,3}\s+(.+)$/);
      html += heading ? "<h3>" + inline(heading[1]) + "</h3>" : "<p>" + inline(line) + "</p>";
    }

    if (inList) html += "</ul>";
    return html || "<p>No release notes were provided.</p>";
  }

  function downloadLink(label, url) {
    if (!url) return "";
    return '<a href="' + escapeHtml(url) + '">' + escapeHtml(label) + "</a>";
  }

  function sortReleases(list) {
    return list.slice().sort(function (a, b) {
      return new Date(b.date || 0) - new Date(a.date || 0);
    });
  }

  function renderLatest() {
    if (!downloadButton || !summaryLine) return;

    var latest = null;
    for (var i = 0; i < releases.length; i++) {
      if (releases[i].isLatest) { latest = releases[i]; break; }
    }
    if (!latest) latest = releases[0];

    if (!latest) {
      downloadButton.textContent = "Download coming soon";
      downloadButton.setAttribute("aria-disabled", "true");
      downloadButton.href = RELEASES_URL;
      summaryLine.textContent = "No public build is available yet.";
      return;
    }

    var primaryUrl = latest.dmgUrl || latest.zipUrl || latest.htmlUrl;
    if (primaryUrl) {
      downloadButton.href = primaryUrl;
      downloadButton.removeAttribute("aria-disabled");
      downloadButton.textContent = "Download " + versionLabel(latest);
    }

    var format = latest.dmgUrl ? "DMG" : latest.zipUrl ? "ZIP" : "GitHub release";
    var parts = [versionLabel(latest), format, platformLabel(latest), formatDate(latest.date)];
    summaryLine.textContent = parts.filter(Boolean).join(" · ");
  }

  function renderTable() {
    if (!tableBody) return;

    if (!releases.length) {
      // Apps that have not shipped yet say so here rather than showing an
      // empty table; the wording can be overridden per page.
      var section = document.getElementById("release-notes");
      var message = (section && section.getAttribute("data-empty-message")) ||
        "Release notes are coming soon. Every version will be listed here once the first one ships.";
      tableBody.innerHTML =
        '<tr><td colspan="4" class="releases-empty">' + escapeHtml(message) + "</td></tr>";
      return;
    }

    var start = page * PAGE_SIZE;
    var rows = releases.slice(start, start + PAGE_SIZE);

    tableBody.innerHTML = rows.map(function (release) {
      var downloads = [
        downloadLink("DMG", release.dmgUrl),
        downloadLink("ZIP", release.zipUrl),
        downloadLink("App Store", release.appStoreUrl),
        downloadLink("GitHub", release.htmlUrl)
      ].filter(Boolean).join("");

      var platform = platformLabel(release);

      return "" +
        "<tr>" +
          '<th scope="row" class="release-version">' +
            escapeHtml(versionLabel(release)) +
            (release.isLatest ? ' <span class="pill">Latest</span>' : "") +
            (platform ? '<span class="release-platform">' + escapeHtml(platform) + "</span>" : "") +
          "</th>" +
          '<td class="release-date">' + escapeHtml(formatDate(release.date)) + "</td>" +
          '<td class="release-body">' + markdownToHtml(stripTitleHeading(release.body, release)) + "</td>" +
          '<td class="release-links">' + (downloads || "&mdash;") + "</td>" +
        "</tr>";
    }).join("");
  }

  function renderPager() {
    if (!pager) return;

    var pages = Math.ceil(releases.length / PAGE_SIZE);
    if (pages < 2) {
      pager.hidden = true;
      return;
    }

    pager.hidden = false;
    if (pagerStatus) pagerStatus.textContent = "Page " + (page + 1) + " of " + pages;
    if (prevButton) prevButton.disabled = page === 0;
    if (nextButton) nextButton.disabled = page >= pages - 1;
  }

  function render() {
    renderTable();
    renderPager();
  }

  function goTo(next) {
    var pages = Math.max(1, Math.ceil(releases.length / PAGE_SIZE));
    page = Math.min(Math.max(next, 0), pages - 1);
    render();
    var heading = document.getElementById("release-notes");
    if (heading) heading.scrollIntoView({ behavior: "smooth", block: "start" });
  }

  if (prevButton) prevButton.addEventListener("click", function () { goTo(page - 1); });
  if (nextButton) nextButton.addEventListener("click", function () { goTo(page + 1); });

  var data = window.APP_RELEASES;
  releases = Array.isArray(data) ? sortReleases(data) : [];
  renderLatest();
  render();
})();
